[tool.poetry]
name = "webhooks"
version = "0.1.0"
description = ""
authors = ["Varderes Barsegyan <vbarsegyan@gomaestro.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
